OPENWEATHER_API_KEY = "97e8d2cd60987df69fe3253b804cc26b"


# Configuration SMTP pour emails
[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = "jeromevitoff@gmail.com"
sender_password = "elmyzagnoulcdnmz" 